[platformio]
default_envs = esp32s3_n16r8

[env:esp32s3_n16r8]
platform = espressif32 @ 7.1.0
board = esp32-s3-devkitc-1
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi

board_build.partitions = partitions_16MB.csv
board_build.filesystem = littlefs

upload_port = COM6
upload_speed = 460800
monitor_port = COM6
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, direct

build_unflags =
    -Os
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1

build_flags =
    -O2
    -DBOARD_HAS_PSRAM
    -DARDUINO_RUNNING_CORE=0
    -DARDUINO_EVENT_RUNNING_CORE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_LITTLEFS_PAGE_SIZE=256
    -DCONFIG_LITTLEFS_OBJ_NAME_LEN=64

lib_deps =
    WiFi
    WebServer
    LittleFS
    FS
    Wire
    HTTPClient
    WiFiClientSecure
    olikraus/U8g2 @ ^2.35.9
